### ISSUE TITLE
Mistake in code sample

### ISSUE THREAD

**Issue by jenscl** [VojtenkoRN/angular2-datatable-serverpagination#4]
There's a mistake in the AppComponent.html file from your code sample. The `(onPageChange)` output in the html code below should be `(mfOnPageChange)`.

`<table class="table table-striped" [mfData]="data" #mf="mfDataTable" 
    [mfRowsOnPage]="5" (onPageChange)="onPageChange($event)" 
    [mfAmountOfRows]="amountOfRows">
`

**Comment by VojtenkoRN** [comment]
Sorry for that
